# PBS flags
queue: express
project: v45
walltime: 1:00:00
ncpus: 1604
mem: 3208GB
jobname: gfdl_2160

collate:
    walltime: 1:00:00
    mem: 32GB
    ncpus: 16
    queue: express
    flags: -v
    mpi: true
    restart: true

runlog: true

# Model config
model: mom
shortpath: /short/v45
exe: fms_MOM_SIS.intel14.fpe3.O2
input: 
    - mom025/mask_2160
    - mom025/levels_50
    - mom025/climatology  
    - mom025/mosaic
    - cnyf2

# Misc
stacksize: unlimited

qsub_flags: -lother=hyperthread
